name: followers_list
publish_to: none

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter
  component_library:
    path: ../../component_library
  user_repository:
    path: ../../user_repository
  activity_repository:
    path: ../../activity_repository
  domain_models:
    path: ../../domain_models
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  infinite_scroll_pagination: ^4.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true