name: quote_repository
publish_to: none

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  fav_qs_api_v2:
    path: ../fav_qs_api_v2
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.1.0
