name: user_repository
publish_to: none

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  fav_qs_api_v2:
    path: ../fav_qs_api_v2
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  doublequotes:
    path: ../../


dev_dependencies:
  lints: ^5.1.0
  #mockito: ^5.4.4
