name: fav_qs_api_v2
publish_to: none

environment:
  sdk: '3.6.0-334.4.beta'

dependencies:
  dio: ^5.7.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  
dev_dependencies:
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
