// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FV6cwGwN4VuR92Z3haD4jQUtKMgZiag',
    appId: '1:474559301695:web:c8094c59568052a740108a',
    messagingSenderId: '474559301695',
    projectId: 'wonder-words-33abf',
    authDomain: 'wonder-words-33abf.firebaseapp.com',
    databaseURL: 'https://wonder-words-33abf-default-rtdb.firebaseio.com',
    storageBucket: 'wonder-words-33abf.appspot.com',
    measurementId: 'G-FX38CEN433',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQg79iyuiX_ggAp_lDHAB21RSvZmBVTCk',
    appId: '1:474559301695:android:d12800ad49ca05d340108a',
    messagingSenderId: '474559301695',
    projectId: 'wonder-words-33abf',
    databaseURL: 'https://wonder-words-33abf-default-rtdb.firebaseio.com',
    storageBucket: 'wonder-words-33abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk61FWez7jIJGcvSrjw6AbSjcUuXZ-ZGY',
    appId: '1:474559301695:ios:8674badd0ae8c1e340108a',
    messagingSenderId: '474559301695',
    projectId: 'wonder-words-33abf',
    databaseURL: 'https://wonder-words-33abf-default-rtdb.firebaseio.com',
    storageBucket: 'wonder-words-33abf.appspot.com',
    iosBundleId: 'com.example.wonderwords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk61FWez7jIJGcvSrjw6AbSjcUuXZ-ZGY',
    appId: '1:474559301695:ios:97f25c341f27418940108a',
    messagingSenderId: '474559301695',
    projectId: 'wonder-words-33abf',
    databaseURL: 'https://wonder-words-33abf-default-rtdb.firebaseio.com',
    storageBucket: 'wonder-words-33abf.appspot.com',
    iosBundleId: 'com.example.wonderwords.RunnerTests',
  );
}
