name: key_value_storage
publish_to: none

environment:
  sdk: '3.6.0-216.1.beta'

dependencies:
  hive: ^2.2.3
  meta: ^1.15.0
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  lints: ^5.1.0
  test: ^1.25.8
