name: key_value_storage
publish_to: none

environment:
  sdk: '3.6.0-216.1.beta'

dependencies:
  doublequotes:
    path: ../../
  hive_local_storage: ^1.1.1
  path_provider: ^2.1.4


dev_dependencies:
  hive_generator: ^2.0.1
