arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: quote_list_localizations.dart
output-class: QuoteListLocalizations
project-dir: ../../../
preferred-supported-locales:
  - "en"
  - "sw"
synthetic-package: false
nullable-getter: false
untranslated-messages-file: quote_list_untranslated.dart
