name: quote_list
publish_to: none

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  doublequotes:
    path: ../../../
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  quote_repository:
    path: ../../quote_repository
  user_repository:
    path: ../../user_repository
  monitoring:
    path: ../../monitoring
  bloc_concurrency: ^0.2.5
  infinite_scroll_pagination: ^4.1.0


dev_dependencies:
  lints: ^5.1.0

flutter:
  uses-material-design: true