#This setting tells Flutter the location of our arb files
arb-dir: lib/src/l10n

#Identifies the main arb file
template-arb-file: messages_en.arb

#Tells Flutter how you want it to name the generated Dart file
output-localization-file: component_library_localizations.dart

#Similar to the above, but now, the name of the actual class 
# instead of the file.
output-class: ComponentLibraryLocalizations

#List of preferred-supported-locales
preferred-supported-locales:
  - "en"
  - "sw"

#Path to the main project directory
project-dir: ../../../

#By default, Flutter will generate your localization files 
#under a hidden/synthetic package whose visibility only
# spans the package which you generated the files for.
# Our app, DoubleQuotes, has a multi-package structure, and 
# we'll need to export our localization files so that we'll 
# be able to access them from the main package 
synthetic-package: false

#If set, we'll need to check for nullability whenever accessing a 
# property from our Flutter code, e.g, l10n?.signedInUserGreeting
nullable-getter: false
