arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: activity_list_localizations.dart 
output-class: ActivityListLocalizations
project-dir: ../../../
preferred-supported-locales:
  - "en"
  - "sw"
synthetic-package: false
nullable-getter: false
